language: cpp

sudo: required

compiler:
- clang
- gcc

env:
- PURPOSE=compile
- PURPOSE=unittest
- PURPOSE=compile-with-bazel

before_script:
- ulimit -c unlimited -S       # enable core dumps

after_failure:
- COREFILE=$(find . -maxdepth 2 -name "core*" | head -n 1) # find core file
- if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

before_install:
- wget --no-clobber https://github.com/bazelbuild/bazel/releases/download/0.8.1/bazel_0.8.1-linux-x86_64.deb
- sudo dpkg -i bazel_0.8.1-linux-x86_64.deb

install:
- sudo apt-get install -qq realpath libgflags-dev libprotobuf-dev libprotoc-dev protobuf-compiler libleveldb-dev libgoogle-perftools-dev
- sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo env "PATH=$PATH" cmake . && sudo make && sudo mv libgtest* /usr/lib/ && cd -
- sudo apt-get install -y gdb  # install gdb

script:
- sh build_in_travis_ci.sh
